### PR TITLE
Add a `Constants.sol` Library to Aggregate the Constants

### PR DESCRIPTION
**Pull request by beaushinkle**
This makes it so that our parameters and derived constants are all
defined in one place and one source of truth, which makes it easier to
understand, and harder to introduce bugs and unexpected behavior in the
future.

Tagging @pdyraga and @eth-r and maybe @lukasz-zimnoch for review.

Let me know if there's a better way to do this!

closes https://github.com/keep-network/sortition-pools/issues/158

before:
```
·-------------------------------------------------|----------------------------|-------------|-----------------------------·
|               Solc version: 0.8.9               ·  Optimizer enabled: false  ·  Runs: 200  ·  Block limit: 30000000 gas  │
··················································|····························|·············|······························
|  Methods                                                                                                                 │
······················|···························|··············|·············|·············|···············|··············
|  Contract           ·  Method                   ·  Min         ·  Max        ·  Avg        ·  # calls      ·  eur (avg)  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  addOperator              ·       81734  ·     115884  ·      99551  ·           23  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  makeEligible             ·           -  ·          -  ·      54689  ·            2  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  makeIneligible           ·       29648  ·      33148  ·      32686  ·            9  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  massMakeIneligible       ·           -  ·          -  ·      42352  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  payReward                ·       38615  ·      58796  ·      47367  ·           19  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  updateOperatorWeight     ·       29840  ·      54411  ·      39102  ·            4  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  withdrawIneligible       ·           -  ·          -  ·      44084  ·            4  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  withdrawRewards          ·       54386  ·      79433  ·      60640  ·           20  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  insertOperator           ·      142234  ·     343260  ·     225338  ·          119  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  lock                     ·           -  ·          -  ·      26675  ·           10  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  setRewardIneligibility   ·       38227  ·     245970  ·     107475  ·            3  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  transferOwnership        ·           -  ·          -  ·      29066  ·           23  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  unlock                   ·           -  ·          -  ·      26655  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  updateOperatorStatus     ·       82080  ·     114793  ·      95904  ·            3  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  withdrawIneligible       ·           -  ·          -  ·      54124  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  withdrawRewards          ·       73387  ·      78175  ·      76506  ·            6  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionTreeStub  ·  publicInsertOperator     ·      129065  ·     312967  ·     279793  ·           22  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionTreeStub  ·  publicRemoveLeaf         ·           -  ·          -  ·      98264  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionTreeStub  ·  publicRemoveOperator     ·       69676  ·      99312  ·      77085  ·            4  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionTreeStub  ·  publicSetLeaf            ·      210568  ·     242866  ·     229947  ·            5  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionTreeStub  ·  publicUpdateLeaf         ·           -  ·          -  ·      72756  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  TestBranch         ·  runPickWeightedSlotTest  ·           -  ·          -  ·      27105  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  TokenStub          ·  approveAndCall           ·       63875  ·      94143  ·      82036  ·            5  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  TokenStub          ·  mint                     ·           -  ·          -  ·      71287  ·            4  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  Deployments                                    ·                                          ·  % of limit   ·             │
··················································|··············|·············|·············|···············|··············
|  BranchStub                                     ·           -  ·          -  ·     304299  ·          1 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  PositionStub                                   ·           -  ·          -  ·     292563  ·          1 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  RewardsStub                                    ·           -  ·          -  ·    1689648  ·        5.6 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  RNGStub                                        ·           -  ·          -  ·     276663  ·        0.9 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  SortitionPool                                  ·     4012771  ·    4012783  ·    4012782  ·       13.4 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  SortitionTreeStub                              ·           -  ·          -  ·    1691321  ·        5.6 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  TestBranch                                     ·           -  ·          -  ·     325037  ·        1.1 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  TokenStub                                      ·           -  ·          -  ·    2411896  ·          8 %  ·          -  │
·-------------------------------------------------|--------------|-------------|-------------|---------------|-------------·
```

after
```

·-------------------------------------------------|----------------------------|-------------|-----------------------------·
|               Solc version: 0.8.9               ·  Optimizer enabled: false  ·  Runs: 200  ·  Block limit: 30000000 gas  │
··················································|····························|·············|······························
|  Methods                                                                                                                 │
······················|···························|··············|·············|·············|···············|··············
|  Contract           ·  Method                   ·  Min         ·  Max        ·  Avg        ·  # calls      ·  eur (avg)  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  addOperator              ·       81734  ·     115884  ·      99551  ·           23  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  makeEligible             ·           -  ·          -  ·      54689  ·            2  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  makeIneligible           ·       29648  ·      33148  ·      32686  ·            9  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  massMakeIneligible       ·           -  ·          -  ·      42352  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  payReward                ·       38615  ·      58796  ·      47367  ·           19  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  updateOperatorWeight     ·       29840  ·      54411  ·      39102  ·            4  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  withdrawIneligible       ·           -  ·          -  ·      44084  ·            4  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  RewardsStub        ·  withdrawRewards          ·       54386  ·      79433  ·      60640  ·           20  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  insertOperator           ·      142234  ·     343260  ·     225338  ·          119  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  lock                     ·           -  ·          -  ·      26675  ·           10  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  setRewardIneligibility   ·       38227  ·     245970  ·     107475  ·            3  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  transferOwnership        ·           -  ·          -  ·      29066  ·           23  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  unlock                   ·           -  ·          -  ·      26655  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  updateOperatorStatus     ·       82080  ·     114793  ·      95904  ·            3  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  withdrawIneligible       ·           -  ·          -  ·      54124  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionPool      ·  withdrawRewards          ·       73387  ·      78175  ·      76506  ·            6  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionTreeStub  ·  publicInsertOperator     ·      129065  ·     312967  ·     279793  ·           22  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionTreeStub  ·  publicRemoveLeaf         ·           -  ·          -  ·      98264  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionTreeStub  ·  publicRemoveOperator     ·       69676  ·      99312  ·      77085  ·            4  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionTreeStub  ·  publicSetLeaf            ·      210568  ·     242866  ·     229947  ·            5  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  SortitionTreeStub  ·  publicUpdateLeaf         ·           -  ·          -  ·      72756  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  TestBranch         ·  runPickWeightedSlotTest  ·           -  ·          -  ·      27105  ·            1  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  TokenStub          ·  approveAndCall           ·       63875  ·      94143  ·      82036  ·            5  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  TokenStub          ·  mint                     ·           -  ·          -  ·      71287  ·            4  ·          -  │
······················|···························|··············|·············|·············|···············|··············
|  Deployments                                    ·                                          ·  % of limit   ·             │
··················································|··············|·············|·············|···············|··············
|  BranchStub                                     ·           -  ·          -  ·     304299  ·          1 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  PositionStub                                   ·           -  ·          -  ·     292563  ·          1 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  RewardsStub                                    ·           -  ·          -  ·    1689648  ·        5.6 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  RNGStub                                        ·           -  ·          -  ·     276663  ·        0.9 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  SortitionPool                                  ·     4012771  ·    4012783  ·    4012782  ·       13.4 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  SortitionTreeStub                              ·           -  ·          -  ·    1691333  ·        5.6 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  TestBranch                                     ·           -  ·          -  ·     325037  ·        1.1 %  ·          -  │
··················································|··············|·············|·············|···············|··············
|  TokenStub                                      ·           -  ·          -  ·    2411896  ·          8 %  ·          -  │
·-------------------------------------------------|--------------|-------------|-------------|---------------|-------------·
```

image

### CODE REVIEW

**Comment by pdyraga** [comment]
Can we install https://www.npmjs.com/package/hardhat-gas-reporter in this repository and confirm it is not changing gas consumption?

**Comment by beaushinkle** [comment]
Okay - I got everything installed and ran the `npm test` with the gas reporter on both `main` and this branch, pasted the results above, and included a diff. It looks like the only measurable difference is a 23 gas increase to `SortitionTreeStub`, which is probably noise.

Is there a different way to measure?

**Comment by eth-r** [comment]
That's a deployment difference, I'm not sure where exactly it would be coming from but it seems fine.

**Review by lukasz-zimnoch — DISMISSED** [review]
LGTM! Let's just fix the red linter build

**Review by lukasz-zimnoch — APPROVED** [review]

**Pull request merged**
